### ISSUE TITLE
2.1.1

### ISSUE THREAD

**Issue by komato3huk** [adeptio-project/adeptio#20]
file wallet.dat has LSN 1/32776, past end of log at 1/476
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
file wallet.dat has LSN 1/32776, past end of log at 1/476
Commonly caused by moving a database from one database environment
to another without clearing the database LSNs, or by removing all of
the log files from a database environment
DB_ENV->log_flush: LSN of 1/32776 past current end-of-log of 1/476
Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment
PANIC: DB_RUNRECOVERY: Fatal error, run database recovery
wallet.dat: unable to flush page: 628

Not sync and not work

**Comment by adeptio-project** [comment]
Please try to start the wallet with `-reindex` parameter

**Comment by komato3huk** [comment]
No. I sync from 0 blocks. And reindex no effects.

**Comment by adeptio-project** [comment]
Can you provide more info about your system?
`Windows/Linux`
Wallet version?
`v2.1.1.0 ?`
ScreenShot of wallet sync stop.

Did you used a bootstrap? Because your error indicates:
`Database environment corrupt; the wrong log files may have been removed or incompatible database files imported from another environment`

**Comment by adeptio-project** [comment]
No answer, closing in
